"""add division for management_departments

Revision ID: 13e7dd2db4bc
Revises: d499d9aa3b68
Create Date: 2025-10-30 11:22:57.050337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e7dd2db4bc'
down_revision: Union[str, Sequence[str], None] = 'd499d9aa3b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('management_departments', sa.Column('division', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('management_departments', 'division')
    # ### end Alembic commands ###
