"""add departnents secretaries

Revision ID: 1d8fdfaa5a2e
Revises: 525f328df83d
Create Date: 2025-10-14 11:43:59.409119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8fdfaa5a2e'
down_revision: Union[str, Sequence[str], None] = '525f328df83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secretaries', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_secretaries_department_id'), 'secretaries', ['department_id'], unique=False)
    op.create_foreign_key(None, 'secretaries', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'secretaries', type_='foreignkey')
    op.drop_index(op.f('ix_secretaries_department_id'), table_name='secretaries')
    op.drop_column('secretaries', 'department_id')
    # ### end Alembic commands ###
