"""update option for assignee_id

Revision ID: 1fb007703b25
Revises: b23bd97f99a0
Create Date: 2025-10-10 15:33:45.736964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb007703b25'
down_revision: Union[str, Sequence[str], None] = 'b23bd97f99a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
