"""update request_item

Revision ID: 29c13321d390
Revises: 89c1de481386
Create Date: 2025-11-06 14:57:45.695270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c13321d390'
down_revision: Union[str, Sequence[str], None] = '89c1de481386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_item', sa.Column('description_executor', sa.Text(), nullable=True))
    op.add_column('request_item', sa.Column('description_organization', sa.Text(), nullable=True))
    op.drop_column('requests', 'description_executor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('description_executor', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('request_item', 'description_organization')
    op.drop_column('request_item', 'description_executor')
    # ### end Alembic commands ###
