"""secretary_id nullable true

Revision ID: 44c30c88e688
Revises: 00be9d17b07a
Create Date: 2026-06-22 09:01:16.278161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c30c88e688'
down_revision: Union[str, Sequence[str], None] = '00be9d17b07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'secretary_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'secretary_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
