"""add deadline_planning

Revision ID: 46a4c8856bf1
Revises: 65bffd4ff5c6
Create Date: 2025-11-07 16:27:52.674047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a4c8856bf1'
down_revision: Union[str, Sequence[str], None] = '65bffd4ff5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_item', sa.Column('deadline_planning', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_item', 'deadline_planning')
    # ### end Alembic commands ###
