"""add deadlines in request_item

Revision ID: 47ad6617e47b
Revises: 29c13321d390
Create Date: 2025-11-06 16:47:02.731848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47ad6617e47b'
down_revision: Union[str, Sequence[str], None] = '29c13321d390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_item', sa.Column('deadline_executor', sa.DateTime(timezone=True), nullable=True))
    op.add_column('request_item', sa.Column('deadline_organization', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('request_item', 'deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_item', sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('request_item', 'deadline_organization')
    op.drop_column('request_item', 'deadline_executor')
    # ### end Alembic commands ###
