"""update user role optional

Revision ID: 525f328df83d
Revises: cf968f9e96c8
Create Date: 2025-10-14 10:19:53.836121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '525f328df83d'
down_revision: Union[str, Sequence[str], None] = 'cf968f9e96c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SECRETARY', 'JUDGE', 'MANAGEMENT', 'EXECUTOR', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SECRETARY', 'JUDGE', 'MANAGEMENT', 'EXECUTOR', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###
