"""add type userrole

Revision ID: 605c2e6e0151
Revises: 13e7dd2db4bc
Create Date: 2025-10-30 11:39:50.371624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605c2e6e0151'
down_revision: Union[str, Sequence[str], None] = '13e7dd2db4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('SECRETARY', 'JUDGE', 'MANAGEMENT', 'MANAGEMENT_DEPARTMENT', 'EXECUTOR', 'EXECUTOR_ORGANIZATION', name='userrole'), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
