"""add index in r_i and del executors in requests

Revision ID: 65bffd4ff5c6
Revises: 47ad6617e47b
Create Date: 2025-11-07 10:23:55.550977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bffd4ff5c6'
down_revision: Union[str, Sequence[str], None] = '47ad6617e47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_request_item_executor_id'), 'request_item', ['executor_id'], unique=False)
    op.create_index(op.f('ix_request_item_executor_organization_id'), 'request_item', ['executor_organization_id'], unique=False)
    op.drop_index(op.f('ix_requests_executor_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_executor_organization_id'), table_name='requests')
    op.drop_constraint(op.f('requests_executor_id_fkey'), 'requests', type_='foreignkey')
    op.drop_constraint(op.f('requests_executor_organization_id_fkey'), 'requests', type_='foreignkey')
    op.drop_column('requests', 'executor_organization_id')
    op.drop_column('requests', 'executor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('executor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('executor_organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('requests_executor_organization_id_fkey'), 'requests', 'executor_organizations', ['executor_organization_id'], ['id'])
    op.create_foreign_key(op.f('requests_executor_id_fkey'), 'requests', 'executors', ['executor_id'], ['id'])
    op.create_index(op.f('ix_requests_executor_organization_id'), 'requests', ['executor_organization_id'], unique=False)
    op.create_index(op.f('ix_requests_executor_id'), 'requests', ['executor_id'], unique=False)
    op.drop_index(op.f('ix_request_item_executor_organization_id'), table_name='request_item')
    op.drop_index(op.f('ix_request_item_executor_id'), table_name='request_item')
    # ### end Alembic commands ###
