"""add index user_id request_history

Revision ID: 6dbab7795026
Revises: 1fb007703b25
Create Date: 2025-10-13 11:54:21.068539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbab7795026'
down_revision: Union[str, Sequence[str], None] = '1fb007703b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_code_key'), 'departments', type_='unique')
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_request_history_user_id'), 'request_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_history_user_id'), table_name='request_history')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.create_unique_constraint(op.f('departments_code_key'), 'departments', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
