"""add description_management_department

Revision ID: 89c1de481386
Revises: b556518d8dee
Create Date: 2025-11-05 18:02:03.560301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c1de481386'
down_revision: Union[str, Sequence[str], None] = 'b556518d8dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('description_management_department', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'description_management_department')
    # ### end Alembic commands ###
