"""del item_id from item

Revision ID: b23bd97f99a0
Revises: dacb5f1f0917
Create Date: 2025-10-10 15:32:10.869446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23bd97f99a0'
down_revision: Union[str, Sequence[str], None] = 'dacb5f1f0917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'request_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_requests_item_id'), table_name='requests')
    op.drop_constraint(op.f('requests_item_id_fkey'), 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'users', ['assignee_id'], ['id'])
    op.drop_column('requests', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key(op.f('requests_item_id_fkey'), 'requests', 'items', ['item_id'], ['id'])
    op.create_index(op.f('ix_requests_item_id'), 'requests', ['item_id'], unique=False)
    op.drop_constraint(None, 'request_history', type_='foreignkey')
    # ### end Alembic commands ###
