"""add size in request_documents

Revision ID: b556518d8dee
Revises: 605c2e6e0151
Create Date: 2025-11-05 16:22:57.692969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b556518d8dee'
down_revision: Union[str, Sequence[str], None] = '605c2e6e0151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_documents', sa.Column('size', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'request_documents', 'requests', ['request_id'], ['id'])
    op.create_foreign_key(None, 'request_history', 'requests', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request_history', type_='foreignkey')
    op.drop_constraint(None, 'request_documents', type_='foreignkey')
    op.drop_column('request_documents', 'size')
    # ### end Alembic commands ###
