"""add description_executor

Revision ID: cc22f348fdec
Revises: 1d8fdfaa5a2e
Create Date: 2025-10-15 14:54:47.370822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc22f348fdec'
down_revision: Union[str, Sequence[str], None] = '1d8fdfaa5a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'request_documents', 'requests', ['request_id'], ['id'])
    op.add_column('requests', sa.Column('description_executor', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'description_executor')
    op.drop_constraint(None, 'request_documents', type_='foreignkey')
    # ### end Alembic commands ###
