"""update all users and requests

Revision ID: cf968f9e96c8
Revises: 6dbab7795026
Create Date: 2025-10-14 10:03:36.654877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf968f9e96c8'
down_revision: Union[str, Sequence[str], None] = '6dbab7795026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SECRETARY', 'JUDGE', 'MANAGEMENT', 'EXECUTOR', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('executors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executors_user_id'), 'executors', ['user_id'], unique=True)
    op.create_table('judges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judges_department_id'), 'judges', ['department_id'], unique=False)
    op.create_index(op.f('ix_judges_user_id'), 'judges', ['user_id'], unique=True)
    op.create_table('management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_user_id'), 'management', ['user_id'], unique=True)
    op.create_table('secretaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secretaries_judge_id'), 'secretaries', ['judge_id'], unique=False)
    op.create_index(op.f('ix_secretaries_user_id'), 'secretaries', ['user_id'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_type', sa.Enum('MATERIAL', 'TECHNICAL', 'OPERATIONAL', 'EMERGENCY', name='requesttype'), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('secretary_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('management_id', sa.Integer(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ),
    sa.ForeignKeyConstraint(['management_id'], ['management.id'], ),
    sa.ForeignKeyConstraint(['secretary_id'], ['secretaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_department_id'), 'requests', ['department_id'], unique=False)
    op.create_index(op.f('ix_requests_executor_id'), 'requests', ['executor_id'], unique=False)
    op.create_index(op.f('ix_requests_judge_id'), 'requests', ['judge_id'], unique=False)
    op.create_index(op.f('ix_requests_management_id'), 'requests', ['management_id'], unique=False)
    op.create_index(op.f('ix_requests_registration_number'), 'requests', ['registration_number'], unique=True)
    op.create_index(op.f('ix_requests_request_type'), 'requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_requests_secretary_id'), 'requests', ['secretary_id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_table('request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('REGISTERED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_history_request_id'), 'request_history', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_history_user_id'), 'request_history', ['user_id'], unique=False)
    op.create_table('request_item',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'item_id')
    )
    op.create_foreign_key(None, 'request_documents', 'requests', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request_documents', type_='foreignkey')
    op.drop_table('request_item')
    op.drop_index(op.f('ix_request_history_user_id'), table_name='request_history')
    op.drop_index(op.f('ix_request_history_request_id'), table_name='request_history')
    op.drop_table('request_history')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_secretary_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_request_type'), table_name='requests')
    op.drop_index(op.f('ix_requests_registration_number'), table_name='requests')
    op.drop_index(op.f('ix_requests_management_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_judge_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_executor_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_department_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_secretaries_user_id'), table_name='secretaries')
    op.drop_index(op.f('ix_secretaries_judge_id'), table_name='secretaries')
    op.drop_table('secretaries')
    op.drop_index(op.f('ix_management_user_id'), table_name='management')
    op.drop_table('management')
    op.drop_index(op.f('ix_judges_user_id'), table_name='judges')
    op.drop_index(op.f('ix_judges_department_id'), table_name='judges')
    op.drop_table('judges')
    op.drop_index(op.f('ix_executors_user_id'), table_name='executors')
    op.drop_table('executors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
