"""add managment_departments and executor_organizations

Revision ID: d499d9aa3b68
Revises: cc22f348fdec
Create Date: 2025-10-30 10:04:06.305888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd499d9aa3b68'
down_revision: Union[str, Sequence[str], None] = 'cc22f348fdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executors', sa.Column('management_department_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_executors_management_department_id'), 'executors', ['management_department_id'], unique=False)
    op.create_foreign_key(None, 'executors', 'management_departments', ['management_department_id'], ['id'])
    op.create_foreign_key(None, 'request_documents', 'requests', ['request_id'], ['id'])
    op.add_column('requests', sa.Column('management_department_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('executor_organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_requests_executor_organization_id'), 'requests', ['executor_organization_id'], unique=False)
    op.create_index(op.f('ix_requests_management_department_id'), 'requests', ['management_department_id'], unique=False)
    op.create_foreign_key(None, 'requests', 'management_departments', ['management_department_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'executor_organizations', ['executor_organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_index(op.f('ix_requests_management_department_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_executor_organization_id'), table_name='requests')
    op.drop_column('requests', 'executor_organization_id')
    op.drop_column('requests', 'management_department_id')
    op.drop_constraint(None, 'request_documents', type_='foreignkey')
    op.drop_constraint(None, 'executors', type_='foreignkey')
    op.drop_index(op.f('ix_executors_management_department_id'), table_name='executors')
    op.drop_column('executors', 'management_department_id')
    # ### end Alembic commands ###
